/**
 * tarotAssets.ts - Quản lý hình ảnh 78 lá bài Tarot Rider-Waite & Lưng bài
 */

export const TAROT_CARD_BACK = require('../../assets/tarot/card-back.png');

export const TAROT_IMAGE_MAP: Record<string, any> = {
  '0-fool': require('../../assets/tarot/cards/00-fool.jpg'),
  '1-magician': require('../../assets/tarot/cards/01-magician.jpg'),
  '2-high-priestess': require('../../assets/tarot/cards/02-high-priestess.jpg'),
  '3-empress': require('../../assets/tarot/cards/03-empress.jpg'),
  '4-emperor': require('../../assets/tarot/cards/04-emperor.jpg'),
  '5-hierophant': require('../../assets/tarot/cards/05-hierophant.jpg'),
  '6-lovers': require('../../assets/tarot/cards/06-lovers.jpg'),
  '7-chariot': require('../../assets/tarot/cards/07-chariot.jpg'),
  '8-strength': require('../../assets/tarot/cards/08-strength.jpg'),
  '9-hermit': require('../../assets/tarot/cards/09-hermit.jpg'),
  '10-wheel-of-fortune': require('../../assets/tarot/cards/10-wheel-of-fortune.jpg'),
  '11-justice': require('../../assets/tarot/cards/11-justice.jpg'),
  '12-hanged-man': require('../../assets/tarot/cards/12-hanged-man.jpg'),
  '13-death': require('../../assets/tarot/cards/13-death.jpg'),
  '14-temperance': require('../../assets/tarot/cards/14-temperance.jpg'),
  '15-devil': require('../../assets/tarot/cards/15-devil.jpg'),
  '16-tower': require('../../assets/tarot/cards/16-tower.jpg'),
  '17-star': require('../../assets/tarot/cards/17-star.jpg'),
  '18-moon': require('../../assets/tarot/cards/18-moon.jpg'),
  '19-sun': require('../../assets/tarot/cards/19-sun.jpg'),
  '20-judgement': require('../../assets/tarot/cards/20-judgement.jpg'),
  '21-world': require('../../assets/tarot/cards/21-world.jpg'),
  'wands-01': require('../../assets/tarot/cards/minor/wands/01.jpg'),
  'wands-02': require('../../assets/tarot/cards/minor/wands/02.jpg'),
  'wands-03': require('../../assets/tarot/cards/minor/wands/03.jpg'),
  'wands-04': require('../../assets/tarot/cards/minor/wands/04.jpg'),
  'wands-05': require('../../assets/tarot/cards/minor/wands/05.jpg'),
  'wands-06': require('../../assets/tarot/cards/minor/wands/06.jpg'),
  'wands-07': require('../../assets/tarot/cards/minor/wands/07.jpg'),
  'wands-08': require('../../assets/tarot/cards/minor/wands/08.jpg'),
  'wands-09': require('../../assets/tarot/cards/minor/wands/09.jpg'),
  'wands-10': require('../../assets/tarot/cards/minor/wands/10.jpg'),
  'wands-11': require('../../assets/tarot/cards/minor/wands/11.jpg'),
  'wands-12': require('../../assets/tarot/cards/minor/wands/12.jpg'),
  'wands-13': require('../../assets/tarot/cards/minor/wands/13.jpg'),
  'wands-14': require('../../assets/tarot/cards/minor/wands/14.jpg'),
  'cups-01': require('../../assets/tarot/cards/minor/cups/01.jpg'),
  'cups-02': require('../../assets/tarot/cards/minor/cups/02.jpg'),
  'cups-03': require('../../assets/tarot/cards/minor/cups/03.jpg'),
  'cups-04': require('../../assets/tarot/cards/minor/cups/04.jpg'),
  'cups-05': require('../../assets/tarot/cards/minor/cups/05.jpg'),
  'cups-06': require('../../assets/tarot/cards/minor/cups/06.jpg'),
  'cups-07': require('../../assets/tarot/cards/minor/cups/07.jpg'),
  'cups-08': require('../../assets/tarot/cards/minor/cups/08.jpg'),
  'cups-09': require('../../assets/tarot/cards/minor/cups/09.jpg'),
  'cups-10': require('../../assets/tarot/cards/minor/cups/10.jpg'),
  'cups-11': require('../../assets/tarot/cards/minor/cups/11.jpg'),
  'cups-12': require('../../assets/tarot/cards/minor/cups/12.jpg'),
  'cups-13': require('../../assets/tarot/cards/minor/cups/13.jpg'),
  'cups-14': require('../../assets/tarot/cards/minor/cups/14.jpg'),
  'swords-01': require('../../assets/tarot/cards/minor/swords/01.jpg'),
  'swords-02': require('../../assets/tarot/cards/minor/swords/02.jpg'),
  'swords-03': require('../../assets/tarot/cards/minor/swords/03.jpg'),
  'swords-04': require('../../assets/tarot/cards/minor/swords/04.jpg'),
  'swords-05': require('../../assets/tarot/cards/minor/swords/05.jpg'),
  'swords-06': require('../../assets/tarot/cards/minor/swords/06.jpg'),
  'swords-07': require('../../assets/tarot/cards/minor/swords/07.jpg'),
  'swords-08': require('../../assets/tarot/cards/minor/swords/08.jpg'),
  'swords-09': require('../../assets/tarot/cards/minor/swords/09.jpg'),
  'swords-10': require('../../assets/tarot/cards/minor/swords/10.jpg'),
  'swords-11': require('../../assets/tarot/cards/minor/swords/11.jpg'),
  'swords-12': require('../../assets/tarot/cards/minor/swords/12.jpg'),
  'swords-13': require('../../assets/tarot/cards/minor/swords/13.jpg'),
  'swords-14': require('../../assets/tarot/cards/minor/swords/14.jpg'),
  'pentacles-01': require('../../assets/tarot/cards/minor/pentacles/01.jpg'),
  'pentacles-02': require('../../assets/tarot/cards/minor/pentacles/02.jpg'),
  'pentacles-03': require('../../assets/tarot/cards/minor/pentacles/03.jpg'),
  'pentacles-04': require('../../assets/tarot/cards/minor/pentacles/04.jpg'),
  'pentacles-05': require('../../assets/tarot/cards/minor/pentacles/05.jpg'),
  'pentacles-06': require('../../assets/tarot/cards/minor/pentacles/06.jpg'),
  'pentacles-07': require('../../assets/tarot/cards/minor/pentacles/07.jpg'),
  'pentacles-08': require('../../assets/tarot/cards/minor/pentacles/08.jpg'),
  'pentacles-09': require('../../assets/tarot/cards/minor/pentacles/09.jpg'),
  'pentacles-10': require('../../assets/tarot/cards/minor/pentacles/10.jpg'),
  'pentacles-11': require('../../assets/tarot/cards/minor/pentacles/11.jpg'),
  'pentacles-12': require('../../assets/tarot/cards/minor/pentacles/12.jpg'),
  'pentacles-13': require('../../assets/tarot/cards/minor/pentacles/13.jpg'),
  'pentacles-14': require('../../assets/tarot/cards/minor/pentacles/14.jpg'),
};

export function getTarotCardImage(cardId: string): any {
  return TAROT_IMAGE_MAP[cardId] || TAROT_CARD_BACK;
}
