import { ImageSourcePropType } from 'react-native';

export type IndicatorCategory = 'core' | 'potential' | 'karmic' | 'bridge' | 'cycle' | 'chart';

export interface NumerologyCardMeta {
  id: string;
  number: string;
  key: string;
  nameVi: string;
  nameEn: string;
  category: IndicatorCategory;
  categoryNameVi: string;
  image: ImageSourcePropType;
  description: string;
}

export const NUMEROLOGY_CARDS: NumerologyCardMeta[] = [
  {
    id: 'card_01_walksOfLife',
    number: '01',
    key: 'walksOfLife',
    nameVi: 'Số Đường Đời',
    nameEn: 'Life Path',
    category: 'core',
    categoryNameVi: 'Cốt Lõi',
    image: require('../../assets/cards/card_01_walksOfLife.jpg'),
    description: 'Chỉ số quan trọng nhất, định hình quỹ đạo cuộc đời, tính cách bẩm sinh và bài học chính bạn cần trải nghiệm.',
  },
  {
    id: 'card_02_mission',
    number: '02',
    key: 'mission',
    nameVi: 'Số Sứ Mệnh',
    nameEn: 'Mission / Destiny',
    category: 'core',
    categoryNameVi: 'Cốt Lõi',
    image: require('../../assets/cards/card_02_mission.jpg'),
    description: 'Mục đích tối thượng và dấu ấn di sản mà bạn được sinh ra để cống hiến cho cuộc đời này.',
  },
  {
    id: 'card_03_soul',
    number: '03',
    key: 'soul',
    nameVi: 'Số Linh Hồn',
    nameEn: 'Soul Urge',
    category: 'core',
    categoryNameVi: 'Cốt Lõi',
    image: require('../../assets/cards/card_03_soul.jpg'),
    description: 'Khát khao sâu kín nhất trong tâm hồn, động lực nội tại thúc đẩy mọi cảm xúc và lựa chọn cá nhân.',
  },
  {
    id: 'card_04_personality',
    number: '04',
    key: 'personality',
    nameVi: 'Số Nhân Cách',
    nameEn: 'Personality',
    category: 'core',
    categoryNameVi: 'Cốt Lõi',
    image: require('../../assets/cards/card_04_personality.jpg'),
    description: 'Chiếc áo phong cách bên ngoài, ấn tượng đầu tiên mà người xung quanh cảm nhận về khí chất của bạn.',
  },
  {
    id: 'card_05_dateOfBirth',
    number: '05',
    key: 'dateOfBirth',
    nameVi: 'Số Ngày Sinh',
    nameEn: 'Birthday Number',
    category: 'core',
    categoryNameVi: 'Cốt Lõi',
    image: require('../../assets/cards/card_05_dateOfBirth.jpg'),
    description: 'Tài năng thiên bẩm và món quà đặc biệt được vũ trụ ban tặng ngay khi bạn cất tiếng khóc chào đời.',
  },
  {
    id: 'card_06_mature',
    number: '06',
    key: 'mature',
    nameVi: 'Số Trưởng Thành',
    nameEn: 'Maturity Number',
    category: 'potential',
    categoryNameVi: 'Tiềm Năng',
    image: require('../../assets/cards/card_06_mature.jpg'),
    description: 'Sức mạnh hợp nhất giữa Đường đời và Sứ mệnh, thăng hoa rực rỡ nhất ở giai đoạn trung niên.',
  },
  {
    id: 'card_07_balance',
    number: '07',
    key: 'balance',
    nameVi: 'Số Cân Bằng',
    nameEn: 'Balance Number',
    category: 'potential',
    categoryNameVi: 'Tiềm Năng',
    image: require('../../assets/cards/card_07_balance.jpg'),
    description: 'Điểm tựa tinh thần và phản xạ ứng xử giúp bạn lấy lại bình tĩnh trước những thử thách bất ngờ.',
  },
  {
    id: 'card_08_rationalThinking',
    number: '08',
    key: 'rationalThinking',
    nameVi: 'Tư Duy Lý Trí',
    nameEn: 'Rational Thought',
    category: 'potential',
    categoryNameVi: 'Tiềm Năng',
    image: require('../../assets/cards/card_08_rationalThinking.jpg'),
    description: 'Phương thức não bộ phân tích thông tin, tư duy logic và đưa ra các quyết định quan trọng.',
  },
  {
    id: 'card_09_subconsciousPower',
    number: '09',
    key: 'subconsciousPower',
    nameVi: 'Sức Mạnh Tiềm Thức',
    nameEn: 'Subconscious Power',
    category: 'potential',
    categoryNameVi: 'Tiềm Năng',
    image: require('../../assets/cards/card_09_subconsciousPower.jpg'),
    description: 'Độ nhạy bén trực giác và khả năng bảo vệ bản thân khi đối mặt với khủng hoảng sinh tồn.',
  },
  {
    id: 'card_10_passion',
    number: '10',
    key: 'passion',
    nameVi: 'Đam Mê Ẩn Giấu',
    nameEn: 'Hidden Passion',
    category: 'potential',
    categoryNameVi: 'Tiềm Năng',
    image: require('../../assets/cards/card_10_passion.jpg'),
    description: 'Sở thích cháy bỏng và ngọn lửa nội tâm mang lại cho bạn niềm vui thuần khiết không toan tính.',
  },
  {
    id: 'card_11_attitude',
    number: '11',
    key: 'attitude',
    nameVi: 'Thái Độ Tiếp Cận',
    nameEn: 'Attitude / Approach',
    category: 'potential',
    categoryNameVi: 'Tiềm Năng',
    image: require('../../assets/cards/card_11_attitude.jpg'),
    description: 'Cách bạn phản ứng tức thời với những trải nghiệm mới mẻ và tình huống hàng ngày.',
  },
  {
    id: 'card_12_karmicDebts',
    number: '12',
    key: 'karmicDebts',
    nameVi: 'Con Số Nợ Nghiệp',
    nameEn: 'Karmic Debts',
    category: 'karmic',
    categoryNameVi: 'Nghiệp & Cầu Nối',
    image: require('../../assets/cards/card_12_karmicDebts.jpg'),
    description: 'Những bài học thử thách nghiệp báo (13/4, 14/5, 16/7, 19/1) bạn cần hóa giải để tiến hóa tâm thức.',
  },
  {
    id: 'card_13_missingNumbers',
    number: '13',
    key: 'missingNumbers',
    nameVi: 'Bài Học Số Thiếu',
    nameEn: 'Karmic Lessons',
    category: 'karmic',
    categoryNameVi: 'Nghiệp & Cầu Nối',
    image: require('../../assets/cards/card_13_missingNumbers.jpg'),
    description: 'Những phẩm chất năng lượng còn khuyết trong tên họ, là bài tập rèn luyện nâng cấp bản thân.',
  },
  {
    id: 'card_14_bridgeLifeMission',
    number: '14',
    key: 'bridgeLifeMission',
    nameVi: 'Cầu Nối Đ.Đời - Sứ Mệnh',
    nameEn: 'Bridge Life Path - Mission',
    category: 'bridge',
    categoryNameVi: 'Nghiệp & Cầu Nối',
    image: require('../../assets/cards/card_14_bridgeLifeMission.jpg'),
    description: 'Nhịp cầu hòa giải khoảng cách giữa con người thực tế và lý tưởng cuộc đời của bạn.',
  },
  {
    id: 'card_15_bridgeSoulPersonality',
    number: '15',
    key: 'bridgeSoulPersonality',
    nameVi: 'Cầu Nối L.Hồn - N.Cách',
    nameEn: 'Bridge Soul - Personality',
    category: 'bridge',
    categoryNameVi: 'Nghiệp & Cầu Nối',
    image: require('../../assets/cards/card_15_bridgeSoulPersonality.jpg'),
    description: 'Sự tương thích giữa nội tâm sâu kín bên trong và diện mạo ứng xử bộc lộ ra ngoài.',
  },
  {
    id: 'card_16_bridgeMaturityPassion',
    number: '16',
    key: 'bridgeMaturityPassion',
    nameVi: 'Cầu Nối T.Thành - Đ.Mê',
    nameEn: 'Bridge Maturity - Passion',
    category: 'bridge',
    categoryNameVi: 'Nghiệp & Cầu Nối',
    image: require('../../assets/cards/card_16_bridgeMaturityPassion.jpg'),
    description: 'Chìa khóa chuyển hóa sở thích cá nhân thành thành tựu lớn khi bước vào độ chín của đời người.',
  },
  {
    id: 'card_17_yearIndividual',
    number: '17',
    key: 'yearIndividual',
    nameVi: 'Năm Cá Nhân',
    nameEn: 'Personal Year',
    category: 'cycle',
    categoryNameVi: 'Vận Hạn Chu Kỳ',
    image: require('../../assets/cards/card_17_yearIndividual.jpg'),
    description: 'Dòng chảy năng lượng chủ đạo trong năm hiện tại, báo hiệu cơ hội thuận lợi và điều nên kiêng kỵ.',
  },
  {
    id: 'card_18_monthIndividual',
    number: '18',
    key: 'monthIndividual',
    nameVi: 'Tháng Cá Nhân',
    nameEn: 'Personal Month',
    category: 'cycle',
    categoryNameVi: 'Vận Hạn Chu Kỳ',
    image: require('../../assets/cards/card_18_monthIndividual.jpg'),
    description: 'Nhịp điệu biến chuyển năng lượng trong từng tháng giúp bạn lập kế hoạch ngắn hạn chính xác.',
  },
  {
    id: 'card_19_dayIndividual',
    number: '19',
    key: 'dayIndividual',
    nameVi: 'Ngày Cá Nhân',
    nameEn: 'Personal Day',
    category: 'cycle',
    categoryNameVi: 'Vận Hạn Chu Kỳ',
    image: require('../../assets/cards/card_19_dayIndividual.jpg'),
    description: 'Năng lượng vi mô của ngày hôm nay, chỉ dẫn hành vi và tâm thái thích hợp nhất.',
  },
  {
    id: 'card_20_way',
    number: '20',
    key: 'way',
    nameVi: '4 Đỉnh Cao Cuộc Đời',
    nameEn: '4 Pinnacles',
    category: 'cycle',
    categoryNameVi: 'Vận Hạn Chu Kỳ',
    image: require('../../assets/cards/card_20_way.jpg'),
    description: '4 giai đoạn trưởng thành lớn và những đỉnh cao thành tựu tương ứng theo từng chu kỳ 9 năm.',
  },
  {
    id: 'card_21_challenges',
    number: '21',
    key: 'challenges',
    nameVi: '4 Thách Thức Cuộc Đời',
    nameEn: '4 Challenges',
    category: 'cycle',
    categoryNameVi: 'Vận Hạn Chu Kỳ',
    image: require('../../assets/cards/card_21_challenges.jpg'),
    description: '4 bài học chướng ngại đi kèm với 4 đỉnh cao, rèn luyện bạn trở thành phiên bản kiên cường.',
  },
  {
    id: 'card_22_arrows',
    number: '22',
    key: 'arrows',
    nameVi: '8 Mũi Tên Cá Tính 3x3',
    nameEn: 'Arrows of Individuality',
    category: 'chart',
    categoryNameVi: 'Biểu Đồ Ma Trận',
    image: require('../../assets/cards/card_22_arrows.jpg'),
    description: 'Các trục sức mạnh hoặc mũi tên trống thể hiện ưu thế và điểm yếu cốt tử trong biểu đồ ngày sinh.',
  },
  {
    id: 'card_23_nameChart',
    number: '23',
    key: 'nameChart',
    nameVi: 'Biểu Đồ Tên & Tần Suất',
    nameEn: 'Name Chart Matrix',
    category: 'chart',
    categoryNameVi: 'Biểu Đồ Ma Trận',
    image: require('../../assets/cards/card_23_nameChart.jpg'),
    description: 'Ma trận phân bổ chữ cái của tên họ, chỉ ra năng lượng dồi dào hoặc bài học còn thiếu.',
  },
  {
    id: 'card_24_birthChart',
    number: '24',
    key: 'birthChart',
    nameVi: 'Biểu Đồ Ngày Sinh 3x3',
    nameEn: 'Birth Chart Matrix',
    category: 'chart',
    categoryNameVi: 'Biểu Đồ Ma Trận',
    image: require('../../assets/cards/card_24_birthChart.jpg'),
    description: 'Bản đồ căn nguyên Pythagoras thể hiện 3 tầng: Thể chất (1-4-7), Cảm xúc (2-5-8), và Trí tuệ (3-6-9).',
  },
];
